### PR TITLE
Review card

### PR DESCRIPTION
**Pull request by nairdesigns**
tried to make it as close to the figma design as possible 
image

figma:

image

### CODE REVIEW

**Comment by abauville** [comment]
I like that better than the previous one. I still have some comments though (you know me :p)
- Be careful when copying the figma because we didn't pay much attention to proper spacing and relative sizing on the figma. 
- Now you card has a huge padding on top, and small one on the bottom.
- It also has huge padding on the side. When the card is by itself it looks big to me, especially because your font-size is small erthan what we had in figma... but in the context of the page it might look cool! The jury is still up
- For me the text is a bit small. For the font-size we have a global variable $font-size-base. We should use it as much as possible to ensure the uniformity of font-sizes

**Comment by nairdesigns** [comment]
made the text size into  **$font-size-base**
before
image
after
image

**Comment by nairdesigns** [comment]
padding should be more equal after this 👍

**Comment by nairdesigns** [comment]
padding should be more equal on both top and bottom after this

image

**Pull request merged**
