### PR TITLE
Result card

### PR DESCRIPTION
**Pull request by nairdesigns**
basic structure of the result card finsihed. only need to add back end compatibility

image

### CODE REVIEW

**Comment by nairdesigns** [comment]
still have to fix some coflicts

**Comment by nairdesigns** [comment]
I finished fixing all the conflicts, please merge if you don't see any errors

**Comment by nairdesigns** [comment]
I do notice i have to fix centering the number 

image

**Comment by abauville** [comment]
The comments look like buttons because of the border.
Also the thumbs up and the score are easy to miss. Especially, if there were more comments, they might not even appear on the page. I'm sorry I didn't check the figma design yesterday. I'd rather have a big thumbs up below "Congratulations" and above the comments. Because, leaving a thumbs up is an easy action that most users might do, but leaving is kind of secondary thing

**Comment by abauville** [comment]
Also, now your design is all white with subtle black borders. You could add some of our colors: purple or green for the title or thumb for example

**Comment by nairdesigns** [comment]
here is an improved design with the button at the bottom of congratulations, what do you think? I also removed the rounded class, so it looks more likecomments boxes.

image

**Comment by abauville** [comment]
I'm a bit confused: you don't want to use the review card that you designed here?
Otherwise, the number of vote is very small. But actually, more and more companies (like Instagram) are removing the number of votes from public view. So we could also not show the score, but keep the button and use the score only for internal logic

**Comment by nairdesigns** [comment]
Hey arhtur i'm just basing everythng i do off of the original figma design,  which was this 
image

as for the review card it was like this (on figma)

image

how would you like me to change it?

**Comment by nairdesigns** [comment]
image

image

**Comment by nairdesigns** [comment]
fixed the spacing!

image

**Pull request merged**
