### PR TITLE
Review controller

### PR DESCRIPTION
**Pull request by abauville**
I setup the review controller. It's checked and debugged. Actions are:
- index
- create
- update
I also made a basic index view as an example.
Screen Shot 2022-03-02 at 19 49 44

The view contains two forms: one for voting (thumbs up). Another one to submit a review. If Tom has already submitted a vote, he cancel it by clicking the button. If he already submitted a review, the review form is prefilled and the button says "edit my review" instead of "submit a review". If an review is edited to delete all the text (empty string) it won't show in the list anymore.
Screen Shot 2022-03-02 at 19 50 15

Screen Shot 2022-03-02 at 19 50 04
 
All the logic is handled in the ReviewController#index.
@nairdesigns you can keep the form logic  in the index and replace the rest with your result's page. 
note: for the submit button fontawesome might not work, in which case you can write an HTML submit button instead.

### CODE REVIEW

**Comment by markiecyt** [comment]
I'm not really sure the desire to use a form, rather than a discrete `link_to` using `ajax`. It would have led to a thin controller, avoiding the `fat controller anti-pattern` which conflicts with the `Single Responsibility Principle`. 

Another improvement could be to move a lot of this logic into the `Review` model.

With hindsight, it perhaps would have made sense to have a separate `Vote` model. It is strange UX to have the default value for vote as 1 when not actively voting. 

It works so can merge, but not sure why there are no strong params, surely this would be a security issue?

**Comment by abauville** [comment]
@markiecyt Thanks for the reivew
- About the form vs link_to: the code I put in there is a placeholder for test and an indication for logic. If you prefer a link rather than a form, I have nothing against. I have no experience with ajax and I don't understand it yet. If you know how to use please refactor the code at your leisure.
- If you want to do move some logic to the model, that sounds like a good idea. Feel free to do so.
- We can still separate the models. It's not gonna be such a big job, and for sure the logic would be simpler (at the expense of one more controller and model).
- The vote is not set at one by default: it is at 0 by default (e.g. if you submit only review), clicking the button sets it to 1, click again sets it back to 0.
- About the strong params, that's because it was not appropriate with the find_or_create. In the end I manage to avoid using it, so we could reintroduce the strong params

**Comment by markiecyt** [comment]
> About the strong params, that's because it was not appropriate with the find_or_create. In the end I manage to avoid using it, so we could reintroduce the strong params

Why was it inappropriate? I'm not sure I understand.

> The vote is not set at one by default: it is at 0 by default (e.g. if you submit only review), clicking the button sets it to 1, click again sets it back to 0

https://user-images.githubusercontent.com/87555651/156361408-e6917a2b-f0d2-433d-852a-03ee7f5bd07b.mov

Here you can see the review going up from 8 to 9 without a vote. In the code - https://github.com/abauville/lickwars/blob/d0d1fa02b54eded3b7b8795ea124bce1e1247cfb/db/schema.rb#L79

**Comment by abauville** [comment]
Fair enough, I'll change the default vote value tomorrow

**Pull request merged**
