### PR TITLE
Fix exercise page

### PR DESCRIPTION
**Pull request by nairdesigns**
fixed the format  of the cards. Very responsive. 

image

### CODE REVIEW

**Comment by nairdesigns** [comment]
Hard is now red

image

**Comment by abauville** [comment]
In your current design the items are evenly split (justify-content-between maybe?), but we don't need the status indicator doesn't need that much space, cf. figma design below. When the window gets bigger you shouldn't be able to see cards that large. You can make the container more reactive (e.g. 12 column on small screen, only 6 on medium and 3 on big... or whatever feels right)
Screen Shot 2022-03-02 at 18 01 00
e

**Comment by markiecyt** [comment]
@nairdesigns Is there a reason to not use[ bootstraps tooltips?](https://getbootstrap.com/docs/5.0/components/tooltips/)  

Styling would be easier and then we could avoid the JQuery

**Comment by nairdesigns** [comment]
> @nairdesigns Is there a reason to not use[ bootstraps tooltips?](https://getbootstrap.com/docs/5.0/components/tooltips/)
> 
> Styling would be easier and then we could avoid the JQuery

Okay I actually did not know about tool tips! i will refactor the code accordingly

**Comment by markiecyt** [comment]
It might be easier long term as you could run into the issue of the tooltip sitting on some text otherwise. Bootstrap would be more flexible for quickly changing it to above, or below, or perhaps there's even auto to solve positioning for you 👍🏻

**Comment by nairdesigns** [comment]
just replaced it with tool tip

**Comment by nairdesigns** [comment]
> In your current design the items are evenly split (justify-content-between maybe?), but we don't need the status indicator doesn't need that much space, cf. figma design below. When the window gets bigger you shouldn't be able to see cards that large. You can make the container more reactive (e.g. 12 column on small screen, only 6 on medium and 3 on big... or whatever feels right) Screen Shot 2022-03-02 at 18 01 00 e

working on this right now

**Comment by nairdesigns** [comment]
resized the cards to be col-8 on a desktop screen. also added bold txt to the title because it was hard to tell when the cards were significanlty smaller.

from this:
image

to bold text:
image

**Comment by nairdesigns** [comment]
i also shortened Intermediate to Inter, because it would always mess up with the alignment, especially with the smaller cards

image

**Comment by abauville** [comment]
I'm ok to merge it, but I'm not sure how to resolve the conflict. @nairdesigns can you have a look?

**Comment by nairdesigns** [comment]
i'll fix it right now!

**Comment by nairdesigns** [comment]
I just fixed it no more conflicts!

**Pull request merged**
