### PR TITLE
index page(home page, dashboard)

### PR DESCRIPTION
**Pull request by km111444**
I modified the index page(home page, dashboard).

スクリーンショット 2022-03-01 15 57 13

### CODE REVIEW

**Comment by abauville** [comment]
For in general try to use the color variables found in files stylesheets/config/colors.scss and _bootstrap_variables.scss.

e.g. l 15 : background-color: #83b7b5; 
replace with: background-color: $light-green

Also, I have the impression you coded the CSS for you button in home.scss
Create a CSS component to store your CSS, try not to put it in page specific files

And reuse other CSS components (e.g. buttons) whenever possible

**Comment by km111444** [comment]
I modified.
I'm not confident though. sorry

**Comment by km111444** [comment]
Sorry, everyone! I took so much time on this!
Now I have a more clear sight of scss!😭

スクリーンショット 2022-03-01 17 12 13
1827669a-450d-4221-899c-a16b039647b6.png">

**Comment by abauville** [comment]
Thanks Kanae, お疲れ様です。

**Pull request merged**
