### PR TITLE
User model

### PR DESCRIPTION
**Pull request by abauville**
Model, migration, validation for User

### CODE REVIEW

**Comment by nairdesigns** [comment]
every time i try to run db migrate i get this error
image

and when i try to run the server i get this as well 

image

**Comment by abauville** [comment]
With Postgresql, you need to db:create at the beginning.

**Comment by nairdesigns** [comment]
everything is working fine! i'll merge both branches

**Comment by nairdesigns** [comment]
actually i still don't have write access to the repository 

image

**Pull request merged**
