### PR TITLE
Color modify - created 3 main color variables in our css page

### PR DESCRIPTION
**Pull request by nairdesigns**
**merge the nav bar branch before merging this, to prevent conflicts

image

### CODE REVIEW

**Comment by nairdesigns** [comment]
image

our custom colors are set in the colors css file

image

**Comment by nairdesigns** [comment]
The body now has a greyish tint instead of white hard to see in the picture. attached is pure white for comparison

image


image

**Comment by nairdesigns** [comment]
reupdated them

image


image

**Comment by abauville** [comment]
OK, just move $main-color to colors.scss because it is not a bootstrap color

**Pull request merged**
